---

- name: Apt cache update
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when:
    - ansible_facts.os_family == "Debian"

- name: Apt Upgrade
  ansible.builtin.apt:
    upgrade: true
  when:
    - ansible_facts.os_family == "Debian"